theme = "blowfish"
baseURL = "http://localhost:1313"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30

buildDrafts = false
buildFuture = false

enableEmoji = true

[pagination]
  pagerSize = 12

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
