[[main]]
  name = "Components"
  pageRef = "components"
  weight = 10

[[main]]
  name = "Templates"
  pageRef = "templates"
  weight = 15

[[main]]
  name = ""
  pre = "github"
  url = "https://github.com"
  weight = 20
