[[main]]
  name = "Components"
  pageRef = "components"
  weight = 10

[[main]]
  name = "Contribute"
  pageRef = "contribute"
  weight = 15

[[main]]
  name = ""
  pre = "github"
  url = "https://github.com/extrAI-lab/kinetica"
  weight = 20
